version: '3.9'

services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - ./docker-config/redis/data:/data
  mongo:
    hostname: mongo
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    volumes:
      - ./docker-config/mongo/data/db:/data/db
      - ./docker-config/mongo/data/configdb:/data/configdb
      - ./docker-config/mongo/mongodb-keyfile:/etc/mongodb-keyfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    command: 'mongod --replSet rs0 --keyFile /etc/mongodb-keyfile'
