name: Fly Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_ENV: 'production'
          envkey_SERVER_SCHEME: 'http'
          envkey_SERVER_HOST: '0.0.0.0'
          envkey_SERVER_PORT: 8080
          envkey_SERVER_READ_TIMEOUT: 60
          envkey_JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          envkey_JWT_SECRET_KEY_EXPIRE_MINUTES_COUNT: 15
          envkey_JWT_REFRESH_KEY: ${{ secrets.JWT_REFRESH_KEY }}
          envkey_JWT_REFRESH_KEY_EXPIRE_HOURS_COUNT: 720
          envkey_MONGO_URI: ${{ secrets.MONGO_URI }}
          envkey_REDIS_HOST: ${{ secrets.REDIS_HOST }}
          envkey_REDIS_PORT: ${{ secrets.REDIS_PORT }}
          envkey_REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          envkey_REDIS_DB_NUMBER: ${{ secrets.REDIS_DB_NUMBER }}

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
